# Generated by Django 2.2.7 on 2019-12-25 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='banner name')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
            },
        ),
        migrations.CreateModel(
            name='BannerImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banner', verbose_name='banner image')),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banners.Banner')),
            ],
            options={
                'verbose_name': 'BannerImage',
                'verbose_name_plural': 'BannerImages',
            },
        ),
    ]
