# Generated by Django 2.2.7 on 2020-01-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0002_auto_20191225_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='name_ar',
            field=models.CharField(max_length=50, null=True, verbose_name='banner name'),
        ),
        migrations.AddField(
            model_name='banner',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='banner name'),
        ),
    ]
