# Generated by Django 2.2.7 on 2019-12-28 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20191227_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cart', to='products.Product'),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
