# Generated by Django 2.2.7 on 2019-12-29 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20191227_1628'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0005_auto_20191228_0215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('line1', models.CharField(max_length=100)),
                ('line2', models.CharField(max_length=100)),
                ('line3', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('postalcode', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment_status', models.IntegerField(choices=[(0, 'PAID'), (1, 'UNPAID')])),
                ('fulfillment_status', models.IntegerField(choices=[(0, 'UNFULFILLED'), (1, 'FULFILLED')])),
                ('payment_type', models.IntegerField(choices=[(0, 'COD'), (1, 'CREDIT_CARD')])),
                ('items', models.ManyToManyField(to='products.Product')),
                ('shipping_address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.Address')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
