# Generated by Django 2.2.7 on 2019-12-30 12:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_address_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='fulfillment_status',
            field=models.IntegerField(blank=True, choices=[(0, 'UNFULFILLED'), (1, 'FULFILLED')], default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.IntegerField(blank=True, choices=[(0, 'PAID'), (1, 'UNPAID')], default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.IntegerField(choices=[(0, 'COD'), (1, 'CREDIT_CARD')], default=0),
        ),
    ]
