# Generated by Django 2.2.7 on 2019-12-30 12:41

from django.db import migrations


def delete_all_orders(apps, schema_editor):
    orders = apps.get_model('orders', 'Order')
    orders.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_item'),
    ]

    operations = [migrations.RunPython(delete_all_orders)]
