# Generated by Django 2.2.7 on 2019-12-17 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='cover',
            field=models.ImageField(null=True, upload_to='', verbose_name='Cover Photo'),
        ),
    ]
