# Generated by Django 2.2.7 on 2019-12-22 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20191222_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='varaint_of',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
