# Generated by Django 2.2.7 on 2019-12-22 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productreview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productreview',
            old_name='no_of_stars',
            new_name='rating',
        ),
    ]
