# Generated by Django 2.2.7 on 2019-12-24 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_collection_collectionimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionimage',
            name='alt',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='alt text'),
        ),
    ]
