# Generated by Django 2.2.7 on 2020-01-24 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name_ar',
            field=models.CharField(max_length=50, null=True, verbose_name='product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='product name'),
        ),
    ]
