# Generated by Django 2.2.7 on 2020-01-24 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20200124_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='descrption_ar',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='descrption_en',
            field=models.TextField(default='', null=True),
        ),
    ]
