# Generated by Django 2.2.7 on 2020-01-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20200124_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Sku Key'),
        ),
    ]
