# Generated by Django 2.2.7 on 2020-01-27 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20200127_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreview',
            name='text_ar',
        ),
        migrations.RemoveField(
            model_name='productreview',
            name='text_en',
        ),
        migrations.AddField(
            model_name='category',
            name='name_ar',
            field=models.CharField(max_length=50, null=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Category Name'),
        ),
    ]
