# Generated by Django 2.2.7 on 2020-01-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20200127_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='name_ar',
            field=models.CharField(max_length=50, null=True, verbose_name='collection name'),
        ),
        migrations.AddField(
            model_name='collection',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='collection name'),
        ),
    ]
