# Generated by Django 2.2.7 on 2020-01-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_auto_20200127_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='name_ar',
            field=models.CharField(max_length=50, null=True, verbose_name='Tag name'),
        ),
        migrations.AddField(
            model_name='tag',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Tag name'),
        ),
    ]
