# Generated by Django 2.2.7 on 2020-02-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_auto_20200127_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='products',
            field=models.ManyToManyField(related_name='tags', to='products.Product'),
        ),
    ]
